name: 'acord_data_quality_monitor'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'acord_data_quality_monitor'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"
  - "logs"

# Configuring models
models:
  acord_data_quality_monitor:
    # Config indicated by + and applies to all files under models/staging/
    staging:
      +materialized: view
      +schema: staging
    
    # Config for all files under models/warehouse/
    warehouse:
      +materialized: table
      +schema: warehouse

seeds:
  acord_data_quality_monitor:
    +schema: reference
