acord_data_quality_monitor:
  outputs:
    dev:
      type: duckdb
      path: ./target/acord_dqm.duckdb
      schema: main
      threads: 4
    
    prod:
      type: duckdb
      path: /data/acord_dqm_prod.duckdb
      schema: main
      threads: 8
  
  target: dev
